### ISSUE TITLE
Recruit translators

### ISSUE THREAD

**Issue by sebrock** [Nault/Nault#87]
# Total number of Languages: 20	(Locales covered: 22)
## Phase 1 - 8 locales

- [x] de - German
- [x] en - English
- [x] es - Spanish
- [x] es_419 - Spanish (Latin America and Caribbean)*
- [x] fr - French
- [x] it - Italian
- [x] pt - Portuguese
- [x] pt_BR -Portuguese (Brazil)*

## Phase 2 - 8 locales

- [x] ar - Arabic
- [x] da - Danish
- [x] fa - Persian (Farsi)
- [x] id - Bahasa Indonesia
- [x] nl - Dutch
- [x] ru - Russian
- [x] tr - Turkish
- [x] no - Norwegian

## Phase 3 - 5 locales

- [x] zh_CN - Chinese (China)
- [x] el - Greek
- [x] hi - Hindi
- [x] ja - Japanese
- [x] sv - Swedish
- [x] vi - Vietnamese

*no separate translations
