### ISSUE TITLE
Track and collect translations

### ISSUE THREAD

**Issue by sebrock** [Nault/Nault#88]
#### Check for language completion status, follow up with translators to get ETA, review, and check mark when 100% translation for  language done
 #### Use comments in this thread to document follow up status.
 #### For each completed language, #89  can be performed

# Total number of Languages: 20	(Locales covered: 22)
## Phase 1 - 8 locales

- [ ] de - German
- [ ] en - English
- [ ] es - Spanish
- [ ] es_419 - Spanish (Latin America and Caribbean)*
- [ ] fr - French
- [ ] it - Italian
- [ ] pt - Portuguese
- [ ] pt_BR -Portuguese (Brazil)*

## Phase 2 - 8 locales

- [ ] ar - Arabic
- [ ] da - Danish
- [ ] fa - Persian (Farsi)
- [ ] id - Bahasa Indonesia
- [ ] nl - Dutch
- [ ] ru - Russian
- [ ] tr - Turkish
- [ ] no - Norwegian

## Phase 3 - 5 locales

- [ ] zh_CN - Chinese (China)
- [ ] el - Greek
- [ ] hi - Hindi
- [ ] ja - Japanese
- [ ] sv - Swedish
- [ ] vi - Vietnamese

*no separate translations

**Comment by le-jun** [comment]
De and En seem to be done. Fr is pending https://github.com/Nault/Nault/pull/480.
